### ISSUE TITLE
v1.1 not working with Qt 6

### ISSUE THREAD

**Issue by jacquetc** [stachenov/quazip#99]
Hello,

Great work with the integration with CMake ! 
Yet, I have a problem with Qt 6 : 

CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt5::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "skribisto-data".

I fixed that replacing Qt5 with Qt6 line 58 in
/usr/local/lib64/cmake/QuaZip-Qt5-1.1/QuaZip-Qt5_SharedTargets.cmake

Also, there is no find_package(QuaZip-Qt6)

Hope this help !

**Comment by stachenov** [comment]
That's not really a fix, and I'm amazed that it works.

You built QuaZip for Qt5 (judging by the name of the package), and then just “fix” it by applying random changes. That's asking for trouble.

Just build QuaZip with `-DQUAZIP_QT_MAJOR_VERSION=6` and you *should* be fine. I haven't tested it myself, though.

As a free bonus, these builds are completely co-installable, so you can have both. That's why you have to specify Qt5 or Qt6 in `find_package`, so CMake knows which version of QuaZip you want to use.

**Comment by jacquetc** [comment]
I agree, I was asking for trouble ;-) and I didn't think that it would work... I didn't find the CMake variable, so thank you. 

It's a bit early to find Quazip packaged for Qt6 on Linux distributions (I'm using Fedora) and Qt6 isn't yet available in Flatpak KDE SDK (Qt 5.15.1).

 It's great that you adapted Quazip to Qt6 and I'll try to build it with -DQUAZIP_QT_MAJOR_VERSION=6. I'll report it to you.

Thank you again,
Cyril

**Comment by stachenov** [comment]
Nah, that wasn't me. I don't even have Qt6 installed. But someone sent a PR. So I don't know whether it works, but there's very little Qt6-specific code, except that ugly Qt5Compat because the Qt Team decided nobody needs legacy codecs any more...

**Comment by jacquetc** [comment]
I'm using Quazip in a Flatpak manifest for my software. For your information, I'm using it [here](https://github.com/jacquetc/skribisto/blob/master/package/flatpak/eu.skribisto.skribisto.yml) as such : 
```
  - name: quazip
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=MinSizeRel
    sources:
      - type: archive
        url: https://github.com/stachenov/quazip/archive/v1.1.tar.gz
        sha256: 54edce9c11371762bd4f0003c2937b5d8806a2752dd9c0fd9085e90792612ad0
      - type: shell
        commands:
          - sed -i 's|${CMAKE_ROOT}/Modules|share/cmake|' CMakeLists.txt
```

I would have loved to find this sort of example in your documentation :-)
